// students.js

const studentData = {
    "grade1A": [ "Aarosh",
        "Abdul Haadi",
        "Abdullah",
        "AbuBakar",
        "Affan",
        "Ali",
        "Alisha",
        "Amina",
        "Hassaan",
        "Areej",
        "Ariz",
        "Daksh",
        "Dhruvik",
        "Hashim",
        "Husaina",
        "Kabir",
        "Maira",
        "Marwa",
        "Mohammad Meer",
        "Mohammad Umar",
        "Mohammed Anas",
        "Nainika",
        "Rajvi",
        "Shubham",
        "Imran",
        "Aizah",
        "Hamza",
        "Aizah"],
    "grade1B": [ "Abubakar",
        "Ahmad",
        "Asra",
        "Burhanuddin",
        "Fatemah",
        "Kulsum",
        "Anas",
        "Taha",
        "Zohan",
        "Zain",
        "Arhaan",
        "Azlan",
        "Nabiha",
        "Nashmia",
        "Qirat",
        "Rayyan",
        "Sehrish",
        "Sejal",
        "Shreyas",
        "Sumant",
        "Sidhiksha",
        "Unaib",
        "Zara",
        "Zidan",
        "Tirth",
        "Mahira",
        "Yusha",
        "Ibrahim"],
   
    "grade2A": [ "Ahmed",
        "Ibrahim",
        "Zunaira",
        "Aadya",
        "Hammad",
        "Bushra",
        "Ihaan",
        "Hiba",
        "Dhruv",
        "Fahad",
        "Priyanshu",
        "Hammad",
        "Aaradhy",
        "Hadi",
        "Vighnesh",
        "Kazi",
        "Ayat",
        "Zikra",
        "Mysha",
        "Yusuf",
        "Zaynab",
        "Tanaya",
        "Konain",
        "Adeefa",
        "Yudaansh",
        "Zahan",
        "Liza",
        "Meera",
        "Bhaumik",
        "Hitansh",
        "Mayank",
        "Muntak",
        "Ayesha",
        "Mustafa",
        "Zohan",
        "Rayyan",
        "Abdul Razzaq",
        "Mohinuddin",
        "Abdullah",
        "Abu Bakr",
        "Affan",
        "Aiyaf"]
        ,
   
    "grade3A": [ "Aamina",
    "Aarya",
    "Aditya",
    "Afnan",
    "Ahmad",
    "Aizah",
    "Akira",
    "Alina",
    "Ayaana",
    "Batul",
    "Fatima",
    "Kabir",
    "Mihan",
    "Ahmed",
    "Avesh",
    "Ehan",
    "Hamza",
    "Ibrahim",
    "Ismail",
    "Razi",
    "Zafir",
    "Pratham",
    "Reyansh",
    "Yaquta",
    "Yusuf",
    "Meet"]
    ,
   
    "grade3B": [ "Aarav",
    "Abu Bakar",
    "Alia",
    "Arshan",
    "Drivya",
    "Driya",
    "Hareem",
    "Inaya",
    "Jinansh",
    "Kiyan",
    "Mizaab",
    "Ali",
    "Ahmad",
    "Ibraheem",
    "Momin",
    "Ojaswee",
    "Shanaya",
    "Sonu",
    "Teertha",
    "Tvisha",
    "Veehana",
    "Wafi",
    "Yahya",
    "Yatharth",
    "Zain",
    "Aqsa",
    "Hamna"]        ,
   
    "grade4A": [ "Husain",
    "Fatah",
    "Burhanuddin",
    "Shayan",
    "Jaitik",
    "Jinesh",
    "Muqsit",
    "Fatima",
    "Hriyansh",
    "Hiyansh",
    "Dhairya",
    "Adiba",
    "Asad",
    "Deena",
    "Eliza",
    "Nitya",
    "Ismail",
    "Muhiyuddin",
    "Ibrahim",
    "Aiman",
    "Dhruvi",
    "Abu Yusar",
    "Ahmed Raza",
    "Nisa",
    "Shakeeb",
    "Rahim",
    "Vivaan",
    "Sara",
    "Tahreem"]        ,
   
    "grade5A": [ "Jibreel",
    "Yuvraj",
    "Yusuf",
    "Ezaan",
    "Shayan",
    "Tabish",
    "Yusuf",
    "Zahra",
    "Umar",
    "Yusuf",
    "Maryam",
    "Afi",
    "Sabeel",
    "Aayat",
    "Umar",
    "Ishaque",
    "Aleem",
    "Ashana",
    "Aazain",
    "Yashab",
    "Sara",
    "Rayyan",
    "Arsh"]        ,
   
    "grade6A": [  "Virag",
        "Diyan",
        "Ali",
        "Maaz",
        "Zaid",
        "Abdullah",
        "Jeevansh",
        "Yuaan",
        "Reehab",
        "Adeena",
        "Mustafa",
        "Vaidehi",
        "Yusha",
        "Omair",
        "Arsh",
        "Mishkaat",
        "Sarah",
        "Shuraim",
        "Anas",
        "Aleena",
        "Arnav"]        ,
   
    "grade7A": [ "Hisham",
    "Swaleha",
    "Alinah",
    "Harsh",
    "Iram",
    "Dev",
    "Azhan",
    "Nouman",
    "Yasham",
    "Umar",
    "Yaksh",
    "Abu Bakar",
    "Asadullah",
    "Bhure",
    "Anasha",
    "Zainab",
    "Ziyan",
    "Adi",
    "Hasan",
    "Ishal",
    "Rufayah",
    "Lavesh"]
    ,
   
    "grade8A": [ "Khan",
    "Abu Talha",
    "Liza",
    "Netavi",
    "Aseel",
    "Ali Hasan",
    "Aneeqa",
    "Arshala",
    "Shiza"]
    ,
   
    "grade9A": ["Sanvi",
        "Masoom",
        "Himanshu",
        "Garv",
        "Fatima",
        "AbdurRehman",
        "Usman",
        "Yuaan"]
    ,
   
    "grade10A": [ "Vibhor",
    "Nizamuddin",
    "Firoj",
    "Musa",
    "Ibrahim",
    "Raiyan",
    "Dhruti",
    "Ashraf",
    "Mantasha",
    "Zuhaib",
    "Konain"]
  };
  